databases:
  - name: metrolens_db
    databaseName: metrolens
    user: metrolens_admin
    plan: free

services:
  - type: web
    name: metrolens-backend
    env: docker
    plan: free
    rootDir: backend
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: metrolens_db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: NVIDIA_API_KEY
        value: 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
      - key: GROQ_API_KEY
        value: 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
